"""empty message

Revision ID: 389bf5f92a9e
Revises: 96b05955fe8b
Create Date: 2026-04-05 17:10:04.297427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389bf5f92a9e'
down_revision = '96b05955fe8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=False))
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
