"""empty message

Revision ID: 3f6996d674ef
Revises: 1f99f8933bc9
Create Date: 2026-05-05 13:09:38.853014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6996d674ef'
down_revision = '1f99f8933bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('job', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('relationship_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profile', schema=None) as batch_op:
        batch_op.drop_column('relationship_status')
        batch_op.drop_column('job')
        batch_op.drop_column('education')

    # ### end Alembic commands ###
