"""empty message

Revision ID: a5a3d9a09c58
Revises: 3f6996d674ef
Create Date: 2026-05-05 13:10:18.455037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a3d9a09c58'
down_revision = '3f6996d674ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profile', schema=None) as batch_op:
        batch_op.alter_column('relationship_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('Single', 'Open Relationship', 'Married', name='relationship_status'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profile', schema=None) as batch_op:
        batch_op.alter_column('relationship_status',
               existing_type=sa.Enum('Single', 'Open Relationship', 'Married', name='relationship_status'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
