"""empty message

Revision ID: d926a512a177
Revises: 
Create Date: 2026-04-05 15:06:29.699466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd926a512a177'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Interest',
    sa.Column('interest_ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('interest_ID')
    )
    op.create_table('User',
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_ID'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('Chat',
    sa.Column('chat_ID', sa.Integer(), nullable=False),
    sa.Column('user1_ID', sa.Integer(), nullable=False),
    sa.Column('user2_ID', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user1_ID'], ['User.user_ID'], ),
    sa.ForeignKeyConstraint(['user2_ID'], ['User.user_ID'], ),
    sa.PrimaryKeyConstraint('chat_ID')
    )
    op.create_table('Likes',
    sa.Column('like_ID', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('liked_user_ID', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('LIKE', 'DISLIKE', 'PASS', name='like_type'), nullable=False),
    sa.ForeignKeyConstraint(['liked_user_ID'], ['User.user_ID'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['User.user_ID'], ),
    sa.PrimaryKeyConstraint('like_ID')
    )
    op.create_table('Match',
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('match_user_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_user_ID'], ['User.user_ID'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['User.user_ID'], ),
    sa.PrimaryKeyConstraint('user_ID', 'match_user_ID')
    )
    op.create_table('Profile',
    sa.Column('profile_ID', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('visiblity_status', postgresql.ENUM('PRIVATE', 'PUBLIC', name='account_status'), nullable=False),
    sa.Column('picture_filename', sa.String(length=100), nullable=False),
    sa.Column('gender_preference', postgresql.ENUM('FEM', 'MALE', 'NB', name='gender_preference'), nullable=False),
    sa.Column('wants_children', postgresql.ENUM('DOES_WANT', 'DOES_NOT', name='children_preference'), nullable=False),
    sa.Column('relationship_type_preference', postgresql.ENUM('CASUAL', 'SERIOUS', name='relationship_preference'), nullable=False),
    sa.ForeignKeyConstraint(['user_ID'], ['User.user_ID'], ),
    sa.PrimaryKeyConstraint('profile_ID')
    )
    op.create_table('UserInterest',
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('interest_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_ID'], ['Interest.interest_ID'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['User.user_ID'], ),
    sa.PrimaryKeyConstraint('user_ID', 'interest_ID')
    )
    op.create_table('Bookmarks',
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('Profile_ID', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Profile_ID'], ['Profile.profile_ID'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['User.user_ID'], ),
    sa.PrimaryKeyConstraint('user_ID', 'Profile_ID')
    )
    op.create_table('Message',
    sa.Column('message_ID', sa.Integer(), nullable=False),
    sa.Column('chat_ID', sa.Integer(), nullable=False),
    sa.Column('sender_ID', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_ID'], ['Chat.chat_ID'], ),
    sa.ForeignKeyConstraint(['sender_ID'], ['User.user_ID'], ),
    sa.PrimaryKeyConstraint('message_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Message')
    op.drop_table('Bookmarks')
    op.drop_table('UserInterest')
    op.drop_table('Profile')
    op.drop_table('Match')
    op.drop_table('Likes')
    op.drop_table('Chat')
    op.drop_table('User')
    op.drop_table('Interest')
    # ### end Alembic commands ###
